[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NETLIFY_BUILD_BASE_IMAGE = "noble"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
