// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// next.config.js
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Configuring Next.js like a hydrologist configures a model - with precision and purpose!

/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: ['placeholder.com'], // Add any external image domains here
  },
  // Enable strict mode for better development experience
  reactStrictMode: true,
  
  // For development, let's not use static export yet
  // When deploying, you can choose either i18n or static export
  
  // Option 1: For development with i18n
  // i18n: {
  //   locales: ['en'],
  //   defaultLocale: 'en',
  // },
  
  // Option 2: For static export (uncomment when ready to build for production)
  output: 'export',
  images: {
    unoptimized: true,
  },
  
  // Enable transpilePackages if needed
  transpilePackages: ['maplibre-gl'],
}

module.exports = nextConfig
