// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// next.config.js
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Configuring Next.js like a hydrologist configures a model - with precision and purpose!

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Set the base path to match your GitHub Pages repository name
  basePath: '/portfolio_website_v3',

  // For static export (required for GitHub Pages)
  output: 'export',
  
  // Disable image optimization for static export
  images: {
    unoptimized: true,
    domains: ['placeholder.com'], // Add any external image domains here
  },
  
  // Enable strict mode for better development experience
  reactStrictMode: true,
  
  // GitHub Pages doesn't support trailing slashes
  trailingSlash: false,
  
  // Enable transpilePackages if needed
  transpilePackages: ['maplibre-gl'],
}

module.exports = nextConfig