// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// next.config.js
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Configuring Next.js like a hydrologist configures a model - with precision and purpose!

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Enable static export for Netlify
  output: 'export',
  
  // Disable image optimization for static export
  images: {
    unoptimized: true,
    domains: ['placeholder.com'], // Add any external image domains here
  },
  
  // Enable strict mode for better development experience
  reactStrictMode: true,
  
  // Netlify handles trailing slashes correctly
  trailingSlash: false,
  
  // Enable transpilePackages if needed
  transpilePackages: ['maplibre-gl'],
}

module.exports = nextConfig