// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// postcss.config.js
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Processing styles like water through a watershed - filtering and transforming!

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
