// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// components/layout/Footer.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// The bottom of our watershed - where all information collects before flowing out to sea!

import Link from 'next/link';
import { Separator } from '@/components/ui/separator';
import { GitHubIcon } from '../ui/icons';

/**
 * Footer component with contact information and site links
 * @returns {React.JSX.Element} Footer with navigation and contact info
 */
export default function Footer() {
  const currentYear = new Date().getFullYear();
  
  return (
    <footer className="bg-forest-900 text-white mt-12">
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Column 1: About */}
          <div>
            <h3 className="text-xl font-semibold mb-4 text-white">Devin Hunt</h3>
            <p className="text-forest-100 mb-4">
              Water Resources Engineer with a passion for sustainable water management and
              outdoor exploration.
            </p>
            <p className="text-forest-100">
              Based in California, working across multiple basins to address water resource challenges.
            </p>
          </div>
          
          {/* Column 2: Quick Links */}
          <div>
            <h3 className="text-xl font-semibold mb-4 text-white">Site Navigation</h3>
            <nav className="flex flex-col space-y-2">
              <Link href="/" className="text-forest-100 hover:text-white transition-colors">
                Home
              </Link>
              <Link href="/resume" className="text-forest-100 hover:text-white transition-colors">
                Resume
              </Link>
              <Link href="/portfolio" className="text-forest-100 hover:text-white transition-colors">
                Portfolio
              </Link>
              <Link href="/interests" className="text-forest-100 hover:text-white transition-colors">
                Personal Interests
              </Link>
            </nav>
          </div>
          
          {/* Column 3: Contact */}
          <div>
            <h3 className="text-xl font-semibold mb-4 text-white">Contact</h3>
            <p className="flex items-center text-forest-100 mb-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                <polyline points="22,6 12,13 2,6"></polyline>
              </svg>
              <a href="mailto:contact@devinhunt.com" className="hover:underline">
                contact@devinhunt.com
              </a>
            </p>
            <div className="flex space-x-4 mt-4">
              <a href="https://github.com/dhunt22" target="_blank" rel="noopener noreferrer" className="text-forest-100 hover:text-white transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <GitHubIcon className="mr-2" />
                </svg>
              {/* <p className='flex items-center text-forest-100 mb-2'>
                dhunt22
              </p> */}
              </a>
              <a href="https://www.linkedin.com/in/devinthunt" target="_blank" rel="noopener noreferrer" className="text-forest-100 hover:text-white transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path>
                  <rect x="2" y="9" width="4" height="12"></rect>
                  <circle cx="4" cy="4" r="2"></circle>
                </svg>
              </a>
            </div>
          </div>
        </div>
        
        <Separator className="my-6 bg-forest-700" />
        
        <div className="text-center text-forest-300 text-sm">
          <p>&copy; {currentYear} Devin Hunt. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}
