// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// app/layout.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// The topographic map that guides all other components - hope it doesn't lead us off a cliff!

import './globals.css';
import { Inter } from 'next/font/google';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { Metadata } from 'next';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

// Define the metadata for the application
export const metadata: Metadata = {
  title: 'Devin Hunt - Water Resources Engineer & Explorer',
  description: 'Portfolio of Devin Hunt, a water resources engineer passionate about hydrological challenges and outdoor adventures.',
  keywords: ['hydrologist', 'water resources', 'engineer', 'IWFM', 'geospatial', 'exploration', 'fishing', 'mycology'],
  authors: [{ name: 'Devin Hunt', url: 'https://devinhunt.com' }],
  creator: 'Devin Hunt',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://devinhunt.com',
    title: 'Devin Hunt - Water Resources Engineer & Explorer',
    description: 'Portfolio of Devin Hunt, a water resources engineer passionate about hydrological challenges and outdoor adventures.',
    siteName: 'Devin Hunt Portfolio',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Devin Hunt - Water Resources Engineer & Explorer',
    description: 'Portfolio of Devin Hunt, a water resources engineer passionate about hydrological challenges and outdoor adventures.',
    creator: '@devinhunt',
  },
};

/**
 * RootLayout component that wraps all pages with common layout elements
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components to render within the layout
 * @returns {React.JSX.Element} The complete layout with header, main content, and footer
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Security-Policy" content="
          default-src 'self'; 
          script-src 'self' 'unsafe-inline' 'unsafe-eval' https://app.netlify.com; 
          style-src 'self' 'unsafe-inline'; 
          img-src 'self' data: blob:; 
          font-src 'self'; 
          connect-src 'self' https://app.netlify.com; 
          frame-src 'self' https://app.netlify.com; 
          worker-src 'self' blob:; 
          manifest-src 'self';
        " />
        <Script src="/netlify-config.js" strategy="beforeInteractive" />
      </head>
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
