// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// app/page.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// The home page - where the watershed of information begins

import Image from 'next/image';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';

/**
 * Home page component displaying introduction and highlights
 * @returns {React.JSX.Element} The rendered home page
 */
export default function Home() {
  return (
    <div className="container mx-auto px-4 py-12">
      <section className="mb-16">
        <div className="flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="md:w-1/2">
            <h1 className="text-5xl font-bold text-forest-800 mb-4">
              Devin Hunt
            </h1>
            <h2 className="text-2xl text-forest-600 mb-6">
              Water Resources Engineer & Explorer
            </h2>
            <p className="text-lg mb-6">
              Passionate about understanding and solving water resource challenges in California 
              through data-driven approaches. Skilled in leveraging open-source data, spatial 
              analysis, and groundwater modeling to support sustainable water management.
            </p>
            <div className="flex gap-4">
              <Link href="/resume">
                <Button className="bg-river-600 hover:bg-river-700">View Resume</Button>
              </Link>
              <Link href="/portfolio">
                <Button variant="outline" className="border-forest-600 text-forest-600 hover:bg-forest-50">
                  Explore Portfolio
                </Button>
              </Link>
            </div>
          </div>
          <div className="md:w-1/2 relative">
            <div className="rounded-lg overflow-hidden shadow-lg relative w-full h-[350px]">
              <Image
                src="/images/profile.jpg"
                alt="Devin Hunt in nature"
                className="object-cover"
                fill
                priority
              />
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-4">
                <p className="text-white text-sm italic">
                  "The world is big, and I want to have a good look at it before it gets dark." – John Muir
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="mb-16">
        <h2 className="text-3xl font-semibold text-forest-700 mb-6">Professional Expertise</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="bg-white/90 backdrop-blur-sm">
            <CardHeader>
              <CardTitle>Water Resources Engineering</CardTitle>
            </CardHeader>
            <CardContent>
              <p>
                Development of CA SGMA Groundwater Sustainability Plans (GSPs), groundwater budgets,
                and optimization of recharge and extraction through geospatial analyses.
              </p>
            </CardContent>
          </Card>
          
          <Card className="bg-white/90 backdrop-blur-sm">
            <CardHeader>
              <CardTitle>Geospatial Analysis</CardTitle>
            </CardHeader>
            <CardContent>
              <p>
                Expertise in ArcGIS Pro, QGIS, and cartography. Creating innovative solutions 
                to visualize and analyze water resource data.
              </p>
            </CardContent>
          </Card>
          
          <Card className="bg-white/90 backdrop-blur-sm">
            <CardHeader>
              <CardTitle>Data-Driven Approaches</CardTitle>
            </CardHeader>
            <CardContent>
              <p>
                Utilization of Python, R, and SQL to process large datasets and develop
                automated workflows for water resource management.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      <section>
        <h2 className="text-3xl font-semibold text-forest-700 mb-6">Personal Passions</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <Link href="/interests#exploration" className="group">
            <Card className="bg-white/90 backdrop-blur-sm h-full transition-all duration-300 group-hover:shadow-md">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" className="text-earth-600">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                  </svg>
                  Exploration
                </CardTitle>
                <CardDescription>Discovering remote natural places</CardDescription>
              </CardHeader>
              <CardContent>
                <p>
                  Traveling in my First Generation Tundra to reach desolate areas, always in search of 
                  quieter places to fully immerse in nature.
                </p>
              </CardContent>
            </Card>
          </Link>

          <Link href="/interests#fishing" className="group">
            <Card className="bg-white/90 backdrop-blur-sm h-full transition-all duration-300 group-hover:shadow-md">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" className="text-river-600">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
                  </svg>
                  Fishing
                </CardTitle>
                <CardDescription>Learning about streams from within</CardDescription>
              </CardHeader>
              <CardContent>
                <p>
                  Fishing nearly all water features encountered, understanding how fish tell stories 
                  about water quality, color, cover types, and food sources.
                </p>
              </CardContent>
            </Card>
          </Link>
        </div>
      </section>
    </div>
  );
}
