// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// components/Loading.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Loading states that flow like water - smooth and natural!

import React from 'react';
import { cn } from '@/lib/utils';

interface LoadingProps {
  size?: 'sm' | 'md' | 'lg';
  className?: string;
  text?: string;
}

/**
 * Loading spinner component with different sizes
 */
export function LoadingSpinner({ size = 'md', className }: Omit<LoadingProps, 'text'>) {
  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-8 h-8',
    lg: 'w-12 h-12'
  };

  return (
    <div className={cn('animate-spin rounded-full border-2 border-gray-300 border-t-river-600', sizeClasses[size], className)}>
      <span className="sr-only">Loading...</span>
    </div>
  );
}

/**
 * Loading component with optional text
 */
export function Loading({ size = 'md', className, text = 'Loading...' }: LoadingProps) {
  return (
    <div className={cn('flex flex-col items-center justify-center p-8', className)}>
      <LoadingSpinner size={size} className="mb-4" />
      <p className="text-forest-600 text-sm">{text}</p>
    </div>
  );
}

/**
 * Skeleton loading components for different content types
 */
export function SkeletonCard() {
  return (
    <div className="bg-white/90 backdrop-blur-sm rounded-lg border p-6 animate-pulse">
      <div className="flex justify-between items-start mb-4">
        <div className="space-y-2">
          <div className="h-6 bg-gray-200 rounded w-3/4"></div>
          <div className="h-4 bg-gray-200 rounded w-1/2"></div>
        </div>
        <div className="h-6 bg-gray-200 rounded w-16"></div>
      </div>
      <div className="space-y-2 mb-4">
        <div className="h-4 bg-gray-200 rounded"></div>
        <div className="h-4 bg-gray-200 rounded w-5/6"></div>
        <div className="h-4 bg-gray-200 rounded w-4/6"></div>
      </div>
      <div className="flex gap-2">
        <div className="h-8 bg-gray-200 rounded w-20"></div>
        <div className="h-8 bg-gray-200 rounded w-24"></div>
      </div>
    </div>
  );
}

/**
 * Skeleton for text content
 */
export function SkeletonText({ lines = 3 }: { lines?: number }) {
  return (
    <div className="space-y-2 animate-pulse">
      {Array.from({ length: lines }, (_, i) => (
        <div 
          key={i} 
          className={cn(
            'h-4 bg-gray-200 rounded',
            i === lines - 1 ? 'w-3/4' : 'w-full'
          )}
        />
      ))}
    </div>
  );
}

/**
 * Skeleton for image content
 */
export function SkeletonImage({ className }: { className?: string }) {
  return (
    <div className={cn('bg-gray-200 rounded animate-pulse', className)}>
      <div className="flex items-center justify-center h-full">
        <svg 
          className="w-12 h-12 text-gray-400" 
          fill="currentColor" 
          viewBox="0 0 20 20"
          aria-hidden="true"
        >
          <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
        </svg>
      </div>
    </div>
  );
}

/**
 * Page loading component with multiple skeleton cards
 */
export function PageLoading({ cardCount = 3 }: { cardCount?: number }) {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-8">
        <div className="h-10 bg-gray-200 rounded w-1/4 mb-4 animate-pulse"></div>
        <div className="h-6 bg-gray-200 rounded w-1/2 animate-pulse"></div>
      </div>
      <div className="grid grid-cols-1 gap-8">
        {Array.from({ length: cardCount }, (_, i) => (
          <SkeletonCard key={i} />
        ))}
      </div>
    </div>
  );
}

export default Loading;
