// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// components/resume/ExperienceItem.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Documenting experience like a hydrologist documents water flow - in meticulous detail!

import React from 'react';

/**
 * ExperienceItem props interface
 * @interface
 * @property {string} title - Job title
 * @property {string} company - Company name
 * @property {string} period - Time period of employment
 * @property {string[]} responsibilities - List of job responsibilities
 */
interface ExperienceItemProps {
  title: string;
  company: string;
  period: string;
  responsibilities: string[];
}

/**
 * Component for displaying a work experience item in the resume
 * @param {ExperienceItemProps} props - Component props
 * @returns {React.JSX.Element} Formatted experience item
 */
const ExperienceItem: React.FC<ExperienceItemProps> = ({
  title,
  company,
  period,
  responsibilities,
}) => {
  return (
    <div className="mb-6 last:mb-0">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-2">
        <h3 className="text-lg font-semibold text-forest-800">{title}</h3>
        <span className="text-forest-600 text-sm italic">{period}</span>
      </div>
      <p className="text-forest-700 font-medium mb-2">{company}</p>
      <ul className="list-disc list-outside ml-5 space-y-1">
        {responsibilities.map((responsibility, index) => (
          <li key={index} className="text-forest-800">
            {responsibility}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default ExperienceItem;
