// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// components/resume/ResumeSection.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Organizing resume sections like well-defined watershed basins!

import React from 'react';

/**
 * ResumeSection props interface
 * @interface
 * @property {string} title - Section title
 * @property {React.ReactNode} children - Section content
 */
interface ResumeSectionProps {
  title: string;
  children: React.ReactNode;
}

/**
 * Component for displaying a section in the resume
 * @param {ResumeSectionProps} props - Component props
 * @returns {React.JSX.Element} Formatted resume section
 */
const ResumeSection: React.FC<ResumeSectionProps> = ({ title, children }) => {
  return (
    <section className="mb-6 print:mb-4">
      <h2 className="text-2xl font-semibold text-forest-700 mb-4 pb-2 border-b border-forest-200 print:text-xl">
        {title}
      </h2>
      <div className="mt-4">{children}</div>
    </section>
  );
};

export default ResumeSection;
