// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// lib/accessibility.ts
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Making our site accessible like ensuring clean water reaches everyone!

/**
 * Accessibility utilities and hooks
 */

import { useEffect, useRef, useState } from 'react';
import React from 'react';

/**
 * Hook for managing focus within a modal or dialog
 * @param isOpen - Whether the modal is open
 * @returns Ref for the modal container
 */
export function useFocusTrap(isOpen: boolean) {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!isOpen || !ref.current) return;

    const element = ref.current;
    const focusableElements = element.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    
    const firstElement = focusableElements[0] as HTMLElement;
    const lastElement = focusableElements[focusableElements.length - 1] as HTMLElement;

    const handleTabKey = (e: KeyboardEvent) => {
      if (e.key !== 'Tab') return;

      if (e.shiftKey) {
        if (document.activeElement === firstElement) {
          lastElement.focus();
          e.preventDefault();
        }
      } else {
        if (document.activeElement === lastElement) {
          firstElement.focus();
          e.preventDefault();
        }
      }
    };

    const handleEscapeKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        // Close modal logic should be handled by parent component
        element.dispatchEvent(new CustomEvent('close-modal'));
      }
    };

    element.addEventListener('keydown', handleTabKey);
    element.addEventListener('keydown', handleEscapeKey);
    
    // Focus first element when modal opens
    firstElement?.focus();

    return () => {
      element.removeEventListener('keydown', handleTabKey);
      element.removeEventListener('keydown', handleEscapeKey);
    };
  }, [isOpen]);

  return ref;
}

/**
 * Hook for managing keyboard navigation in lists
 * @param itemCount - Number of items in the list
 * @param onSelect - Callback when an item is selected
 * @returns Current index and key handler
 */
export function useKeyboardNavigation(
  itemCount: number,
  onSelect: (index: number) => void
) {
  const [currentIndex, setCurrentIndex] = useState(-1);

  const handleKeyDown = (e: KeyboardEvent) => {
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setCurrentIndex(prev => (prev + 1) % itemCount);
        break;
      case 'ArrowUp':
        e.preventDefault();
        setCurrentIndex(prev => (prev - 1 + itemCount) % itemCount);
        break;
      case 'Enter':
      case ' ':
        e.preventDefault();
        if (currentIndex >= 0) {
          onSelect(currentIndex);
        }
        break;
      case 'Home':
        e.preventDefault();
        setCurrentIndex(0);
        break;
      case 'End':
        e.preventDefault();
        setCurrentIndex(itemCount - 1);
        break;
    }
  };

  return { currentIndex, handleKeyDown };
}

/**
 * Generate ARIA attributes for better screen reader support
 */
export const aria = {
  /**
   * Generate ARIA attributes for a button that controls another element
   */
  button: (controls?: string, expanded?: boolean) => ({
    'aria-controls': controls,
    'aria-expanded': expanded,
    'aria-haspopup': expanded !== undefined ? 'true' : undefined,
  }),

  /**
   * Generate ARIA attributes for a navigation landmark
   */
  navigation: (label: string) => ({
    role: 'navigation',
    'aria-label': label,
  }),

  /**
   * Generate ARIA attributes for a live region
   */
  liveRegion: (politeness: 'polite' | 'assertive' = 'polite') => ({
    'aria-live': politeness,
    'aria-atomic': 'true',
  }),

  /**
   * Generate ARIA attributes for form validation
   */
  field: (
    invalid?: boolean,
    describedBy?: string,
    required?: boolean
  ) => ({
    'aria-invalid': invalid,
    'aria-describedby': describedBy,
    'aria-required': required,
  }),

  /**
   * Generate ARIA attributes for tabs
   */
  tab: (selected: boolean, controls: string) => ({
    role: 'tab',
    'aria-selected': selected,
    'aria-controls': controls,
    tabIndex: selected ? 0 : -1,
  }),

  /**
   * Generate ARIA attributes for tab panel
   */
  tabPanel: (labelledBy: string) => ({
    role: 'tabpanel',
    'aria-labelledby': labelledBy,
    tabIndex: 0,
  }),
};

/**
 * Color contrast utility functions
 */
export const contrast = {
  /**
   * Calculate relative luminance of a color
   */
  getLuminance(color: string): number {
    const rgb = this.hexToRgb(color);
    if (!rgb) return 0;

    const [r, g, b] = [rgb.r, rgb.g, rgb.b].map(c => {
      c = c / 255;
      return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    });

    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  },

  /**
   * Calculate contrast ratio between two colors
   */
  getContrastRatio(color1: string, color2: string): number {
    const lum1 = this.getLuminance(color1);
    const lum2 = this.getLuminance(color2);
    const lighter = Math.max(lum1, lum2);
    const darker = Math.min(lum1, lum2);
    return (lighter + 0.05) / (darker + 0.05);
  },

  /**
   * Check if contrast meets WCAG standards
   */
  meetsWCAG(color1: string, color2: string, level: 'AA' | 'AAA' = 'AA'): boolean {
    const ratio = this.getContrastRatio(color1, color2);
    return level === 'AA' ? ratio >= 4.5 : ratio >= 7;
  },

  /**
   * Convert hex color to RGB
   */
  hexToRgb(hex: string): { r: number; g: number; b: number } | null {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16),
    } : null;
  },
};

/**
 * Screen reader utilities
 */
export const screenReader = {
  /**
   * Announce message to screen readers
   */
  announce(message: string, priority: 'polite' | 'assertive' = 'polite'): void {
    const announcement = document.createElement('div');
    announcement.setAttribute('aria-live', priority);
    announcement.setAttribute('aria-atomic', 'true');
    announcement.setAttribute('class', 'sr-only');
    announcement.textContent = message;

    document.body.appendChild(announcement);

    setTimeout(() => {
      document.body.removeChild(announcement);
    }, 1000);
  },

  /**
   * Create visually hidden but screen reader accessible text
   */
  onlyText(text: string): React.ReactNode {
    return (
      <span className="sr-only">
        {text}
      </span>
    );
  },
};

/**
 * Motion preference utilities
 */
export const motion = {
  /**
   * Check if user prefers reduced motion
   */
  prefersReducedMotion(): boolean {
    if (typeof window === 'undefined') return false;
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  },

  /**
   * Get animation duration based on user preferences
   */
  getDuration(normalDuration: number): number {
    return this.prefersReducedMotion() ? 0 : normalDuration;
  },

  /**
   * Get CSS class for respectful animations
   */
  getAnimationClass(animationClass: string): string {
    return this.prefersReducedMotion() ? '' : animationClass;
  },
};
