'use client';

import { useTheme } from 'next-themes';
import { useState, useEffect, useMemo } from 'react';

interface ThemeBackgroundOptions {
  lightImage: string;
  darkImage: string;
  overlayLight?: string;
  overlayDark?: string;
  mobileBreakpoint?: number;
}

interface ThemeBackgroundResult {
  mounted: boolean;
  isMobile: boolean;
  resolvedTheme: string | undefined;
  backgroundImage: string;
  /** Resolved plate URL (light or dark) without the url() wrapper. */
  plateSrc: string;
  isDark: boolean;
  animatedSrc?: string;
}

/**
 * Per-page backdrop plate presets (backdrop engine v2). Each page maps to a
 * fixed landscape contour plate with a native hypsometric ramp; the same SVG
 * file is used for the animated (inlined) layer AND the reduced-motion static
 * CSS background, so light/dark image == overlay for a given theme.
 *
 * Files are generated by scripts/build-plates.mjs into public/images/plates/.
 */
export type PlatePage =
  | 'home'
  | 'portfolio'
  | 'ej'
  | 'resume'
  | 'interests'
  | 'notFound';

const platePreset = (page: PlatePage) => {
  const light = `/images/plates/${page}_light.svg`;
  const dark = `/images/plates/${page}_dark.svg`;
  return {
    lightImage: light,
    darkImage: dark,
    overlayLight: light,
    overlayDark: dark,
  } as const;
};

export const PLATE_PRESETS = {
  home: platePreset('home'),
  portfolio: platePreset('portfolio'),
  ej: platePreset('ej'),
  resume: platePreset('resume'),
  interests: platePreset('interests'),
  notFound: platePreset('notFound'),
} as const;

/**
 * Hook for managing theme-aware backgrounds with mobile detection.
 */
export function useThemeBackground(options: ThemeBackgroundOptions): ThemeBackgroundResult {
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  const mobileBreakpoint = options.mobileBreakpoint ?? 768;

  useEffect(() => {
    setMounted(true);

    const checkMobile = () => {
      setIsMobile(window.innerWidth < mobileBreakpoint);
    };

    checkMobile();
    window.addEventListener('resize', checkMobile);

    return () => window.removeEventListener('resize', checkMobile);
  }, [mobileBreakpoint]);

  const isDark = mounted && resolvedTheme === 'dark';

  const plateSrc = useMemo(
    () => (!mounted ? options.lightImage : isDark ? options.darkImage : options.lightImage),
    [mounted, isDark, options.lightImage, options.darkImage],
  );

  const backgroundImage = useMemo(() => `url(${plateSrc})`, [plateSrc]);

  const animatedSrc = !mounted
    ? undefined
    : isDark
    ? options.overlayDark
    : options.overlayLight;

  return {
    mounted,
    isMobile,
    resolvedTheme,
    backgroundImage,
    plateSrc,
    isDark,
    animatedSrc,
  };
}
