'use client';

import { useTheme } from 'next-themes';
import { useState, useEffect, useMemo, useRef } from 'react';

interface ThemeBackgroundOptions {
  /** Static plate (contours only) — painted as a CSS background-image. */
  lightImage: string;
  darkImage: string;
  /** Animated glow (comet system only) — fetched + inlined over the plate. */
  glowLight: string;
  glowDark: string;
  mobileBreakpoint?: number;
}

interface ThemeBackgroundResult {
  mounted: boolean;
  isMobile: boolean;
  resolvedTheme: string | undefined;
  /**
   * Raw static plate URLs (NOT JS-resolved). The component paints both as CSS
   * background-images on `dark:hidden` / `hidden dark:block` siblings so the
   * correct plate is picked by the `.dark` class from SSR and only the visible
   * one is fetched — no SSR-light-then-dark double download, no flash.
   */
  lightPlate: string;
  darkPlate: string;
  /** Resolved animated glow URL (light or dark) — inlined over the plate. */
  glowSrc: string;
  isDark: boolean;
}

/**
 * Per-page backdrop plate presets (backdrop engine v2). Each page maps to a
 * fixed landscape contour plate split into TWO assets per theme:
 *   <page>_<theme>_plate.svg — static contours, painted as a CSS background.
 *   <page>_<theme>_glow.svg  — the animated comet system, fetched + inlined on
 *     top so its CSS motion-path sprites animate WITHOUT re-rasterizing the
 *     giant static plate every frame.
 *
 * Files are generated by scripts/build-plates.mjs into public/images/plates/.
 */
export type PlatePage =
  | 'home'
  | 'portfolio'
  | 'ej'
  | 'resume'
  | 'interests'
  | 'notFound';

const platePreset = (page: PlatePage) => {
  return {
    lightImage: `/images/plates/${page}_light_plate.svg`,
    darkImage: `/images/plates/${page}_dark_plate.svg`,
    glowLight: `/images/plates/${page}_light_glow.svg`,
    glowDark: `/images/plates/${page}_dark_glow.svg`,
  } as const;
};

export const PLATE_PRESETS = {
  home: platePreset('home'),
  portfolio: platePreset('portfolio'),
  ej: platePreset('ej'),
  resume: platePreset('resume'),
  interests: platePreset('interests'),
  notFound: platePreset('notFound'),
} as const;

/**
 * Hook for managing theme-aware backgrounds with mobile detection.
 */
export function useThemeBackground(options: ThemeBackgroundOptions): ThemeBackgroundResult {
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  const mobileBreakpoint = options.mobileBreakpoint ?? 768;
  const lastWidthRef = useRef<number | null>(null);
  const debounceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    setMounted(true);

    // Synchronous initial check on mount.
    lastWidthRef.current = window.innerWidth;
    setIsMobile(window.innerWidth < mobileBreakpoint);

    const handleResize = () => {
      const currentWidth = window.innerWidth;
      // URL-bar collapse is height-only — width stays the same.
      // Bail out immediately to avoid re-rendering the backdrop.
      if (currentWidth === lastWidthRef.current) return;

      // Width actually changed — debounce the state update by ~150 ms so
      // rapid resize drags only trigger one re-render.
      lastWidthRef.current = currentWidth;
      if (debounceTimerRef.current !== null) {
        clearTimeout(debounceTimerRef.current);
      }
      debounceTimerRef.current = setTimeout(() => {
        setIsMobile(currentWidth < mobileBreakpoint);
      }, 150);
    };

    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
      if (debounceTimerRef.current !== null) {
        clearTimeout(debounceTimerRef.current);
      }
    };
  }, [mobileBreakpoint]);

  const isDark = mounted && resolvedTheme === 'dark';

  // The plate is no longer JS-resolved: both URLs are handed to the component,
  // which paints them on theme-gated (`dark:hidden` / `hidden dark:block`)
  // siblings so the browser fetches only the visible one and SSR HTML already
  // references the correct theme.
  const lightPlate = options.lightImage;
  const darkPlate = options.darkImage;

  // The glow is fetched + inlined POST-mount, so resolving it by JS is fine.
  const glowSrc = useMemo(
    () => (!mounted ? options.glowLight : isDark ? options.glowDark : options.glowLight),
    [mounted, isDark, options.glowLight, options.glowDark],
  );

  return {
    mounted,
    isMobile,
    resolvedTheme,
    lightPlate,
    darkPlate,
    glowSrc,
    isDark,
  };
}
