// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// app/portfolio/page.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Showcasing projects like a well-mapped watershed - every tributary leading to my expertise!

'use client';

import { useState, useMemo } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Icon } from '@/components/ui/icons';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import ProjectMap from '@/components/portfolio/ProjectMap';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { PROJECTS, Project, getProjectsByCategory } from '@/lib/portfolio-data';
import { ExternalLinkIcon, GitHubIcon, DownloadIcon } from '@/components/ui/icons/common-icons';

/**
 * Get icon component based on icon type
 * @param iconType - Type of icon to render
 * @returns Icon component
 */
function getIconByType(iconType?: string) {
  switch (iconType) {
    case 'github':
      return <GitHubIcon className="w-4 h-4" />;
    case 'document':
    case 'external':
    case 'website':
      return <ExternalLinkIcon className="w-4 h-4" />;
    case 'download':
      return <DownloadIcon className="w-4 h-4" />;
    default:
      return <ExternalLinkIcon className="w-4 h-4" />;
  }
}

/**
 * ProjectCard component for rendering individual project cards
 * @param project - Project data
 * @param isActive - Whether this project is currently active
 * @param onClick - Click handler
 * @returns Rendered project card
 */
function ProjectCard({ project, isActive, onClick }: {
  project: Project;
  isActive: boolean;
  onClick: () => void;
}) {
  return (
    <Card 
      id={project.id}
      className={`bg-white/90 backdrop-blur-sm transition-all duration-300 cursor-pointer ${
        isActive ? 'border-river-500 shadow-md' : 'hover:shadow-sm'
      }`}
      onClick={onClick}
    >
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="p-6">
          <CardHeader className="p-0 pb-4">
            <div className="flex justify-between items-start mb-2">
              <CardTitle className="text-2xl text-forest-700">{project.title}</CardTitle>
              {project.year && (
                <span className="text-sm text-forest-500 bg-forest-50 px-2 py-1 rounded">
                  {project.year}
                </span>
              )}
            </div>
            <CardDescription className="text-forest-500">{project.description}</CardDescription>
            {project.technologies && (
              <div className="flex flex-wrap gap-2 mt-2">
                {project.technologies.map((tech, idx) => (
                  <span key={idx} className="text-xs bg-river-100 text-river-700 px-2 py-1 rounded-full">
                    {tech}
                  </span>
                ))}
              </div>
            )}
          </CardHeader>
          
          <CardContent className="p-0 pb-4">
            {project.content.map((paragraph, idx) => (
              <p key={idx} className="mb-4 text-sm leading-relaxed">{paragraph}</p>
            ))}
            
            {project.links && project.links.length > 0 && (
              <div className="mt-4 flex flex-wrap gap-2">
                {project.links.map((link, idx) => (
                  <Link key={idx} href={link.href} target="_blank" rel="noopener noreferrer">
                    <Button 
                      variant="outline" 
                      size="sm"
                      className="border-forest-600 text-forest-600 hover:bg-forest-50"
                    >
                      {getIconByType(link.iconType)}
                      {link.label}
                      <ExternalLinkIcon className="w-3 h-3 ml-1" aria-hidden="true" />
                    </Button>
                  </Link>
                ))}
              </div>
            )}
          </CardContent>
        </div>
        
        <div className="relative h-[300px] md:h-auto">
          <ProjectMap projectId={project.id} />
        </div>
      </div>
    </Card>
  );
}

/**
 * Portfolio page component displaying various professional projects
 * @returns {React.JSX.Element} The rendered portfolio page
 */
export default function PortfolioPage() {
  const [activeProject, setActiveProject] = useState('prison-ej');

  // Memoize filtered projects for better performance
  const projectsByCategory = useMemo(() => {
    const categories = {
      all: getProjectsByCategory('all') || [],
      water: getProjectsByCategory('water') || [],
      geospatial: getProjectsByCategory('geospatial') || [],
      research: getProjectsByCategory('research') || []
    };
    
    // Ensure all arrays are valid and have length property
    Object.keys(categories).forEach(key => {
      const categoryKey = key as keyof typeof categories;
      if (!Array.isArray(categories[categoryKey])) {
        categories[categoryKey] = [];
      }
    });
    
    return categories;
  }, []);

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-forest-800 mb-4">Portfolio</h1>
        <p className="text-lg text-forest-600 mb-6">
          A collection of water resources and geospatial projects showcasing data-driven solutions 
          for sustainable water management across California.
        </p>
      </div>
      
      <Tabs defaultValue="all" className="mb-8">
        <div className="relative z-10 mb-8">
          <TabsList className="flex flex-wrap gap-2 mb-6 justify-center sm:justify-start bg-transparent" role="tablist" aria-label="Portfolio project categories">
            <TabsTrigger 
              value="all" 
              id="tab-all"
              className="px-4 py-2 rounded-lg shadow-sm bg-white text-gray-700 hover:bg-gray-100 focus:outline-none text-sm font-semibold data-[state=active]:bg-forest-50 data-[state=active]:text-forest-700 data-[state=active]:border-forest-500 data-[state=active]:border z-20"
            >
              All Projects ({projectsByCategory.all?.length ?? 0})
            </TabsTrigger>
            <TabsTrigger 
              value="water" 
              id="tab-water"
              className="px-4 py-2 rounded-lg shadow-sm bg-white text-gray-700 hover:bg-gray-100 focus:outline-none text-sm font-semibold data-[state=active]:bg-forest-50 data-[state=active]:text-forest-700 data-[state=active]:border-forest-500 data-[state=active]:border z-20"
            >
              Water Resources ({projectsByCategory.water?.length ?? 0})
            </TabsTrigger>
            <TabsTrigger 
              value="geospatial" 
              id="tab-geospatial"
              className="px-4 py-2 rounded-lg shadow-sm bg-white text-gray-700 hover:bg-gray-100 focus:outline-none text-sm font-semibold data-[state=active]:bg-forest-50 data-[state=active]:text-forest-700 data-[state=active]:border-forest-500 data-[state=active]:border z-20"
            >
              Geospatial Analysis ({projectsByCategory.geospatial?.length ?? 0})
            </TabsTrigger>
            <TabsTrigger 
              value="research" 
              id="tab-research"
              className="px-4 py-2 rounded-lg shadow-sm bg-white text-gray-700 hover:bg-gray-100 focus:outline-none text-sm font-semibold data-[state=active]:bg-forest-50 data-[state=active]:text-forest-700 data-[state=active]:border-forest-500 data-[state=active]:border z-20"
            >
              Research ({projectsByCategory.research?.length ?? 0})
            </TabsTrigger>
          </TabsList>
        </div>
        
        {/* Tab Contents */}
        {Object.entries(projectsByCategory).map(([category, projects]) => (
          <TabsContent 
            key={category} 
            value={category} 
            id={`panel-${category}`}
            className="mt-0 relative z-0"
            role="tabpanel"
            aria-labelledby={`tab-${category}`}
          >
            <div className="grid grid-cols-1 gap-8 pt-2">
              {(projects || []).map(project => (
                <ProjectCard
                  key={project.id}
                  project={project}
                  isActive={activeProject === project.id}
                  onClick={() => setActiveProject(project.id)}
                />
              ))}
            </div>
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}
