// Copyright (c) 2025 Devin Hunt contact@devinhunt.com
// app/resume/page.tsx
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// A resume as flowing as a river - hopefully it doesn't run dry during interviews!

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import ResumeSection from '@/components/resume/ResumeSection';
import ExperienceItem from '@/components/resume/ExperienceItem';
import SkillsList from '@/components/resume/SkillsList';

/**
 * Resume page component showing professional experience, education, and skills
 * @returns {React.JSX.Element} The rendered resume page
 */
export default function ResumePage() {
  // Professional skills data
  const professionalSkills = [
    "Teamwork",
    "Multi-project management",
    "Deadline management",
    "Deliverables coordination",
    "Project scope & budget management",
    "Workflow & task planning",
    "In-person collaboration"
  ];

  // Technical skills data
  const technicalSkills = [
    "Integrated Water Flow Model (IWFM)",
    "ArcGIS Pro and Online",
    "QGIS",
    "Python",
    "R",
    "RESTful APIs",
    "SQL",
    "Groundwater Interpolation",
    "Excel LET and LAMBDA",
    "Field Documentation",
    "Cartography"
  ];

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-4xl font-bold text-forest-800">Resume</h1>
        <Button className="bg-river-600 hover:bg-river-700">
          <a href="/resume.pdf" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download PDF
          </a>
        </Button>
      </div>

      <Card className="p-6 mb-8 bg-white/95 print:shadow-none">
        <section className="mb-6 print:mb-4">
          <h2 className="text-3xl font-semibold text-forest-700 mb-2 print:text-2xl">Devin Hunt</h2>
          <h3 className="text-xl text-forest-600 mb-4 print:text-lg">Water Resources Engineer</h3>
          <div className="mb-4">
            <p className="italic">
              Hydrologist passionate about understanding and solving water resource challenges in California through data-driven approaches. Skilled in leveraging open-source data, spatial analysis, and modeling to support sustainable water management. Committed to applying technical expertise to develop innovative solutions for complex hydrological issues.
            </p>
          </div>
        </section>

        <ResumeSection title="Professional Experience">
          <ExperienceItem 
            title="Water Resources Engineer"
            company="Woodard & Curran"
            period="June 2023 - Present"
            responsibilities={[
              "Engineer 2 involved in the development of CA SGMA Groundwater Sustainability Plans (GSPs), groundwater budgets through CA IWFM modeling, and recharge and extraction optimization through geospatial analyses.",
              "Developed new figures, basemap, and layout templates for the Cuyama 2025 GSP using ESRI ArcGIS Pro",
              "Performed annual updates for the CoSANA Model and Cuyama Basin Water Resources Model (CBWRM)",
              "Utilized python, arcpy, and open-source geospatial libraries to automate large dataset processing",
              "Computed Recharge Suitability Index (RSI) scores using open-source geospatial data for the Yuba Subbasins",
              "Executed independent analysis of well sites in Southern California that provide reliable, clean water for future development",
              "Wrote technical memorandums and deliverable packages for clients"
            ]}
          />
          
          <ExperienceItem 
            title="Geospatial Analyst and Programmer"
            company="Geospatial Centroid at Colorado State University"
            period="October 2022 - May 2023"
            responsibilities={[
              "Involved in various spatial projects in Colorado and CONUS. Also provided project planning and technical tutoring for students.",
              "Developed R-Spatial scripts for NASA-Equity and Environmental Justice Grant project: Environmental Justice for Prisons",
              "Held office hours and supported students with any spatial project needs",
              "Utilize R and geospatial libraries to support project work",
              "Designed hexagonal project spotlight decorations for Centroid office",
              "Executed independent analysis of well sites in Southern California that provide reliable, clean water for future development",
              "Wrote technical memorandums and deliverable packages for clients"
            ]}
          />
          
          <ExperienceItem 
            title="Undergraduate Research Assistant"
            company="Colorado State University"
            period="January 2022 - October 2022"
            responsibilities={[
              "Field researcher and data analyst supporting a PhD Dissertation on stream metabolism. Study area was Fraser Experimental Forest, CO across four catchment basins. (Project Lead Lauren Kremer in Watershed Analysis Group)",
              "Constructed Campbell Scientific stream gages and planned on-site solar panel locations",
              "Installed Campbell Scientific, HOBO, and other in-situ sensors",
              "Collected stream geomorphology, velocity-area, and groundwater level measurements",
              "Read data and maintained sensors",
              "Processed water samples for Dissolved Organic Carbon (DOC), and Inorganic Carbon (IC)",
              "Documented all actions taken in the field and laboratory"
            ]}
          />
        </ResumeSection>

        <ResumeSection title="Education">
          <div className="mb-4">
            <h4 className="text-lg font-semibold text-forest-700">Colorado State University</h4>
            <p className="text-forest-600 italic">BS in Watershed Science, Hydrology and Water Resources Science</p>
            <p className="text-forest-600 italic">Minor in Geospatial Information Systems (GIS)</p>
            <p className="mt-2">
              A multi-disciplinary education that enabled me to remotely sense and quantify my favorite natural resource: water.
            </p>
            <div className="mt-3">
              <h5 className="font-medium text-forest-700">Relevant coursework:</h5>
              <ul className="list-disc list-inside mt-1 ml-2">
                <li>Hydraulics and Groundwater flow; Hydrogeology, Soil Physics, Physics I & II</li>
                <li>Data Science; Programming for GIS I & II, Watershed Analysis for Env. Data Science, Watershed Problem Analysis</li>
                <li>Remote Sensing; Geodetic and Near-surface Geophysical Methods, Remote Sensing and Image Interpretation</li>
                <li>Niche Subjects; Snow Hydrology, Field Measurements in Snow Hydrology</li>
              </ul>
            </div>
          </div>
        </ResumeSection>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <ResumeSection title="Professional Skills">
            <SkillsList skills={professionalSkills} />
          </ResumeSection>
          
          <ResumeSection title="Technical Skills">
            <SkillsList skills={technicalSkills} />
          </ResumeSection>
        </div>

        <ResumeSection title="Additional Achievements">
          <div className="mb-2">
            <p className="font-medium">EAGLE SCOUT AWARD, Boy Scouts of America, August 2018</p>
          </div>
          <div>
            <p className="font-medium">WILDERNESS FIRST AID, NOLS Wilderness Medicine, May 2016</p>
          </div>
        </ResumeSection>
      </Card>
    </div>
  );
}
